# Generated by Django 3.2.4 on 2021-06-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
